name: Test
on:
  push:
  pull_request:

jobs:
  validation:
    runs-on: ubuntu-latest
    env:
      CGO_ENABLED: 0
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
      - name: Lint
        run: make lint
      - name: Test
        run: make test
      - name: generate coverage report
        run: make cover
      - name: Codecov
        uses: codecov/codecov-action@v3
